const menu=document.getElementById('menu'),openButton=document.querySelector('.menu-button'),closeButton=document.querySelector('.menu-close');
function setMenu(open){menu.classList.toggle('open',open);menu.setAttribute('aria-hidden',String(!open));openButton.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':''}
openButton.addEventListener('click',()=>setMenu(true));closeButton.addEventListener('click',()=>setMenu(false));menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));document.addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false)});
const translations={
en:{role:'CULTURAL ORGANIZER / RESEARCHER',bio1:'George Litvin (Egor) is a cultural organizer and researcher working at the intersection of contemporary culture, research, and civic initiatives.',bio2:'Born on 16 April 1998 in Moscow. Since 2016, he has been based in Prague, where he develops and participates in cultural, educational, and public projects.',bio3:'He is a co-organizer of KULTURUS, a Prague-based festival of contemporary culture and human rights that brings together artists, researchers, activists, and independent cultural initiatives.',bio4:'George conducts independent research and fieldwork, exploring how people, places, and traditions shape contemporary societies. He has carried out expeditions in India, Japan, and Morocco, visited more than 75 countries, and works on projects related to culture, identity, and social change.','nav.about':'About','nav.expeditions':'Ethnographic expeditions','nav.festivals':'Festivals & forums','nav.research':'Research & publications','facts.born.label':'BORN','facts.based.label':'BASED IN','facts.visited.label':'VISITED','facts.fields.label':'FIELDS','facts.fields.value':'Culture<br>Social research',coming:'Content coming soon.'},
ru:{role:'КУЛЬТУРНЫЙ ОРГАНИЗАТОР / ИССЛЕДОВАТЕЛЬ',bio1:'Егор Литвин — культурный организатор и исследователь, работающий на пересечении современной культуры, исследований и общественных инициатив.',bio2:'Родился 16 апреля 1998 года в Москве. С 2016 года живёт в Праге, где развивает и участвует в культурных, образовательных и общественных проектах.',bio3:'Соорганизатор KULTURUS — пражского фестиваля современной культуры и прав человека, объединяющего художников, исследователей, активистов и независимые культурные инициативы.',bio4:'Егор занимается самостоятельными исследованиями и полевой работой, изучая, как люди, места и традиции формируют современные общества. Проводил экспедиции в Индии, Японии и Марокко, посетил более 75 стран и работает над проектами, связанными с культурой, идентичностью и социальными изменениями.','nav.about':'Обо мне','nav.expeditions':'Этнографические экспедиции','nav.festivals':'Фестивали и форумы','nav.research':'Исследования и публикации','facts.born.label':'РОДИЛСЯ','facts.based.label':'ЖИВЁТ В','facts.visited.label':'ПОСЕТИЛ','facts.fields.label':'НАПРАВЛЕНИЯ','facts.fields.value':'Культура<br>Социальные исследования',coming:'Материалы скоро появятся.'},
cs:{role:'KULTURNÍ ORGANIZÁTOR / VÝZKUMNÍK',bio1:'Egor Litvin je kulturní organizátor a výzkumník, který působí na pomezí současné kultury, výzkumu a občanských iniciativ.',bio2:'Narodil se 16. dubna 1998 v Moskvě. Od roku 2016 žije v Praze, kde se věnuje kulturním, vzdělávacím a veřejným projektům.',bio3:'Je spoluorganizátorem KULTURUS, pražského festivalu současné kultury a lidských práv, který propojuje umělce, výzkumníky, aktivisty a nezávislé kulturní iniciativy.',bio4:'Věnuje se samostatnému výzkumu a terénní práci a zkoumá, jak lidé, místa a tradice formují současné společnosti. Podnikl etnografické expedice v Indii, Japonsku a Maroku, navštívil více než 75 zemí a pracuje na projektech spojených s kulturou, identitou a společenskými změnami.','nav.about':'O mně','nav.expeditions':'Etnografické expedice','nav.festivals':'Festivaly a fóra','nav.research':'Výzkum a publikace','facts.born.label':'NAROZEN','facts.based.label':'ŽIJE V','facts.visited.label':'NAVŠTÍVIL','facts.fields.label':'OBLASTI','facts.fields.value':'Kultura<br>Sociální výzkum',coming:'Obsah bude brzy doplněn.'}};
function setLanguage(lang){const d=translations[lang];if(!d)return;document.querySelectorAll('[data-i18n]').forEach(el=>{if(d[el.dataset.i18n]!==undefined)el.innerHTML=d[el.dataset.i18n]});document.querySelectorAll('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.documentElement.lang=lang;localStorage.setItem('siteLanguage',lang)}
document.querySelectorAll('.lang').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));setLanguage(localStorage.getItem('siteLanguage')||'en');
